language: node_js
node_js:
  - "stable"
  - "10"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi

after_success:
  - npm install prebuild-ci
  - ./node_modules/.bin/prebuild-ci
